### ISSUE TITLE
Checking out repl.py

### ISSUE THREAD

**Issue by janus** [eigenhombre/PyClojure#1]
I can't pinpoint where lexer = lisplexer() is used. And the "print" inside except (EOFError, KeyboardInterrupt): should print a message

**Comment by eigenhombre** [comment]
Thanks for the issue.  The 'print' is just to give a newline when the user exits with control-C.  But, EOFError (end of file) shouldn't print anything, so I changed that.

Regarding the lexer, you do need it.  If you remove it:

$  ./repl.py 
pylisp> (+ 1 1)
'module' object has no attribute 'lexer'
pylisp> 

PLY is doing some strange stuff under the hood which I don't really understand yet, so things look a little odd when you use the lexer and parser.

**Comment by eigenhombre** [comment]
>  git push
> Counting objects: 5, done.
> Delta compression using up to 2 threads.
> Compressing objects: 100% (3/3), done.
> Writing objects: 100% (3/3), 431 bytes, done.
> Total 3 (delta 2), reused 0 (delta 0)
> To git@github.com:eigenhombre/PyClojure.git
>    b446478..b196949  master -> master

**Comment by janus** [comment]
John,

May be I should work with you. I am not really good on any language,
however I know Clojure and Python. I have not done anything pretty great,
but I am trying to get serious .https://github.com/janus

On Tue, Feb 14, 2012 at 5:21 PM, John Jacobsen <
reply@reply.github.com

> wrote:
> 
> Thanks for the issue.  The 'print' is just to give a newline when the user
> exits with control-C.  But, EOFError (end of file) shouldn't print
> anything, so I changed that.
> 
> Regarding the lexer, you do need it.  If you remove it:
> 
> $  ./repl.py
> pylisp> (+ 1 1)
> 'module' object has no attribute 'lexer'
> pylisp>
> 
> PLY is doing some strange stuff under the hood which I don't really
> understand yet, so things look a little odd when you use the lexer and
> parser.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/eigenhombre/PyClojure/issues/1#issuecomment-3962883

## 

*Satajanus  Nig. Ltd

*

**Comment by eigenhombre** [comment]
Hi Janus, the more the merrier.  There is a lot to be done, just jump on in... if you can add to the functionality, feel free to put in a pull request.  I'd appreciate sticking with TDD and a high level of test coverage on the code.  Thanks in advance for contributions.  Cheers,
John
